// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfDh8mVvrfxGl2621g5MPJhCCvTE7T8Zs',
    appId: '1:271995216401:web:2979fcbad4b04d874887b0',
    messagingSenderId: '271995216401',
    projectId: 'project1-5cff9',
    authDomain: 'project1-5cff9.firebaseapp.com',
    storageBucket: 'project1-5cff9.firebasestorage.app',
    measurementId: 'G-18NHE66XHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApRG9HLmgB5uqKngaQI5sGugtf1-T0zHY',
    appId: '1:271995216401:android:f79d215cff63db0a4887b0',
    messagingSenderId: '271995216401',
    projectId: 'project1-5cff9',
    storageBucket: 'project1-5cff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMPi2MZb6okvOoh-1Oat4ivoK9er4Z1vU',
    appId: '1:271995216401:ios:1def23965286db804887b0',
    messagingSenderId: '271995216401',
    projectId: 'project1-5cff9',
    storageBucket: 'project1-5cff9.firebasestorage.app',
    iosBundleId: 'com.example.projec1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMPi2MZb6okvOoh-1Oat4ivoK9er4Z1vU',
    appId: '1:271995216401:ios:1def23965286db804887b0',
    messagingSenderId: '271995216401',
    projectId: 'project1-5cff9',
    storageBucket: 'project1-5cff9.firebasestorage.app',
    iosBundleId: 'com.example.projec1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfDh8mVvrfxGl2621g5MPJhCCvTE7T8Zs',
    appId: '1:271995216401:web:cf28dcb41c377e1e4887b0',
    messagingSenderId: '271995216401',
    projectId: 'project1-5cff9',
    authDomain: 'project1-5cff9.firebaseapp.com',
    storageBucket: 'project1-5cff9.firebasestorage.app',
    measurementId: 'G-D0FDVBMM88',
  );

}